INSERT INTO occupations (name, occupation) VALUES
('Amy',     'Doctor'),
('Ben',     'Doctor'),
('Clara',   'Doctor'),
('Daniel',  'Doctor'),
('Elena',   'Doctor'),
('Frank',   'Doctor'),
('Grace',   'Doctor'),
('Henry',   'Doctor'),
('Isabel',  'Doctor'),
('Jacob',   'Doctor'),
('Karen',   'Doctor'),
('Liam',    'Doctor'),
('Mia',     'Doctor'),

('Nina',    'Professor'),
('Oscar',   'Professor'),
('Paula',   'Professor'),
('Quentin', 'Professor'),
('Rita',    'Professor'),
('Samuel',  'Professor'),
('Tara',    'Professor'),
('Ursula',  'Professor'),
('Victor',  'Professor'),
('Wendy',   'Professor'),
('Xavier',  'Professor'),
('Yvonne',  'Professor'),
('Zack',    'Professor'),

('Ariana',  'Singer'),
('Bruno',   'Singer'),
('Camila',  'Singer'),
('Drake',   'Singer'),
('Ed',      'Singer'),
('Fiona',   'Singer'),
('Gwen',    'Singer'),
('Harry',   'Singer'),
('Iggy',    'Singer'),
('Justin',  'Singer'),
('Katy',    'Singer'),
('Lorde',   'Singer'),
('Maluma',  'Singer'),

('Adam',    'Actor'),
('Bella',   'Actor'),
('Chris',   'Actor'),
('Daisy',   'Actor'),
('Ethan',   'Actor'),
('Freya',   'Actor'),
('George',  'Actor'),
('Holly',   'Actor'),
('Ian',     'Actor'),
('Julia',   'Actor'),
('Keanu',   'Actor'),
('Leonardo','Actor'),
('Meryl',   'Actor');
